---
- hosts: all
  tasks:
  - name: Make sure groups adm exists
    group: name=adm gid=4 state=present

  - name: Make sure group sudo exists (Hello CentOS)
    group: name=sudo gid=27

  tasks:
    - name: Create Vasiliy Pupkin
      user:
        name: vpupkin
        uid: 2002
        group: adm
        home: /home/vpupkin
        password: '{{ root_password }}'
        update_password: on_create
      tags: vpupkin
    - copy: src="{{ inventory_dir }}/credentials/ssh_pubkeys/vpupkin" dest=/etc/ssh/keys/
      tags: vpupkin

- hosts: clone1:jira:goldproxy:jira2
  tasks:
  - user: name=spetrov uid=2004 group=adm home=/home/spetrov groups=sudo
    tags: spetrov
  - copy: src="{{ inventory_dir }}/credentials/ssh_pubkeys/spetrov" dest=/etc/ssh/keys/
    tags: spetrov

- hosts: main:main2:sandbox
  tasks:
  - user: name=svoronin uid=2006 group=adm home=/home/svoronin shell=/bin/bash groups=sudo
    tags: svoronin
  - copy: src="{{ inventory_dir }}/credentials/ssh_pubkeys/svoronin" dest=/etc/ssh/keys/
    tags: svoronin

########## Superuser Becoming Rules ###############
- hosts: main:clfw01:clfw02:utm:mail:goldproxy
  tasks:
  - user: name=vpupkin groups=sudo append=yes
    tags: vpupkin

########## Server specific rules ###############
- hosts: quagga_servers
  tasks:
  - user: name=exampleuser groups=quagga append=yes
    tags: quagga

- hosts: main
  tasks:
  - user: name={{ item }} groups=openvpn append=yes
    with_items: [exampleuser,vpupkin,svoronin]
    tags: openvpn

- hosts: breeze
  tasks:
    - user: name=nagios uid=1001 group=nagios
    - copy: src="{{ inventory_dir }}/credentials/ssh_pubkeys/nagios" dest=/etc/ssh/keys/

