---
- hosts: kvm_servers
  vars:
  - name: newguestname
  - vg: vg0

  tasks:
  - block:
    - virt:
        name: "{{ name }}" 
        state: destroyed
    - virt:
        name: "{{ name }}"
        command: undefine
      tags: undefine
    - mount: 
        name: "/mnt/{{ name }}"
        state: unmounted
      become: true
    - mount:
        name: "/mnt/{{ name }}"
        state: absent
      become: true
    - shell: kpartx -d /dev/mapper/{{ vg }}-{{ name }}
      become: true
    - lvol:
        vg: '{{ vg }}'
        lv: '{{ name }}'
        state: absent
        force: yes
    - local_action: command rm "{{ inventory_dir }}/host_vars/{{ name }}"
    ignore_errors: True
