---
mail_root: /var/mail
mail_log_dir: '{{ mail_root }}/log'
mail_server_name: '{{ inventory_hostname }}.{{ domain }}'
postfix_db_name: postfix
postfix_db_user: postfix
postfix_db_password: ChangeMe-CotDol3swo
postfix_main_cf:
  myhostname: '{{ mail_server_name }}'
  mydestination: $myhostname
  virtual_mailbox_base: '{{ mail_root }}'
  smtpd_tls_cert_file: '/etc/pki/realms/{{ mail_server_name }}/default.pem'
  smtpd_tls_key_file: '/etc/pki/realms/{{ mail_server_name }}/default.pem'
  smtpd_milters: unix:/spamass/spamass.sock
  smtpd_client_message_rate_limit: 3
  smtpd_client_event_limit_exceptions:
  smtpd_recipient_restrictions: >-
    permit_mynetworks
      permit_sasl_authenticated
      check_sender_access hash:/etc/postfix/sender_access
      check_recipient_access hash:/etc/postfix/recipient_access
      reject_unauth_destination
      reject_rbl_client zen.spamhaus.org
      reject_rbl_client bl.spamcop.net
      reject_unknown_client_hostname
      reject_invalid_helo_hostname
      reject_non_fqdn_helo_hostname
      reject_unknown_helo_hostname
      reject_non_fqdn_sender
      reject_unknown_sender_domain
      reject_unverified_sender
      reject_unknown_recipient_domain
      reject_non_fqdn_recipient
      reject_unauth_pipelining
      reject_unlisted_recipient
      check_policy_service inet:localhost:10023
  smtpd_relay_restrictions: >-
    permit_mynetworks
      permit_sasl_authenticated
      reject_unauth_destination
      check_sender_access hash:/etc/postfix/sender_access
      check_recipient_access hash:/etc/postfix/recipient_access
      check_policy_service unix:private/policy-spf
  smtp_destination_concurrency_limit: 2
  smtp_destination_rate_delay: 1s
  smtp_extra_recipient_limit: 10

roundcube_update: yes
roundcube_version: 1.3
roundcube_path: /opt/roundcube
roundcube_log_dir: /var/log/roundcube
roundcube_smtp_log: true
roundcube_log_logins: true
roundcube_log_session: false
roundcube_sql_debug: false
roundcube_imap_debug: false
roundcube_ldap_debug: false
roundcube_smtp_debug: false
roundcube_db_name: roundcube
roundcube_db_user: roundcube
roundcube_db_password: '{{ postfix_db_password }}'
roundcube_des_key_path: '{{ inventory_dir }}/credentials/{{ inventory_hostname }}/roundcube_des_key'
roundcube_language: en_US

dovecot_db_user: dovecot
dovecot_db_password: '{{ postfix_db_password }}'
fail2ban_ignoreip: '127.0.0.1/8 192.168.0.0/16'

postfixadmin_version: 3.1
postfixadmin_allow:
- 10.0.0.0/8
- 192.168.0.0/16

spam_whitelist_to: []
