---
backup_rsync_opts:
- "--exclude=*.wav"
- "--exclude=*.sln*"
- "--exclude=*.png"
- "--exclude=*.jpg"
- "--exclude=*.swp"
- "--exclude=*~"
- "--exclude=*.dpkg-dist"
- "--exclude=*.old"
- "--exclude=*.bak"
- "--exclude=*.sav"

backup_dest: '{{ inventory_dir }}/backup'

backup_src_groups:
  all_servers:
  - /etc/network/interfaces
  - /etc/fstab
  - /etc/rc.local
  - /etc/cron.d
  fw_servers:
  - /etc/network/fw
  - /etc/keepalived
  kvm_servers:
  - /etc/libvirt/qemu
  nginx_servers:
  - /etc/nginx
  elk_servers:
  - /srv/docker-elk
  mail_servers:
  - /etc/postfix
  squid_servers:
  - /etc/squid
  quagga_servers:
  - /etc/quagga
  - /etc/network/iptables
  asterisk_servers:
  - /etc/asterisk
  postgresql_servers:
  - /etc/postgresql
  odoo_servers:
  - /etc/odoo
  caddy2_servers:
  - /etc/caddy2
  nagios_servers:
  - "{{ nagios_object_dir | d('/usr/local/nagios/etc/objects') }}" 
  moinmoin_servers:
  - /etc/moin
  docker_servers:
  - /etc/docker

backup_src_hosts:
  somehostnameinventoryname:
  - /a/path/to/backup

backup_skip: False
